# DS 3000/CS 3200 Lab 1

Due: Tuesday May 12 in-class

### Submission Instructions
Upload this `ipynb` file to GitHub as per the instructions in Part 4, and then to Gradescope.  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh `Kernel > Restart & Run All` just before uploading the `ipynb` file to GitHub and verify that the correct version is represented on Gradescope.

#### Note:
Future Labs/Homeworks do not need to be submitted via GitHub; I'm only asking you to do it on this Lab to practice with using GitHub (as it will be important to be familiar with its usage for the project). For some of you this is likely already second nature.

### Tips for success
- Collaborate: bounce ideas off of each other, if you are having trouble you can ask your classmates or Dr. Gerber for help with specific issues, however...
- [(See)](http://www.northeastern.edu/osccr/academic-integrity), i.e. you are welcome to **talk about/discuss** (*not* show or allow each other to copy your answers to) the problems.

# Part 1 (40 points): Intro to Markdown

You will use the markdown language in formatting parts of your project. Use it below to create your own brief wikipedia-esque description of a topic related to International Government and Politics. 

Your mini-wiki page must include:
- three headers: a title, subtitle and subsubtitle (the #, ##, ### syntax)
- an embedded image from a web address (use an [image hosting site](https://makeawebsitehub.com/free-photo-hosting/) if you'd like to upload your own)
- a **markdown** table of size at least 9 cells (i.e. 3 by 3, or 5 by 2)
- a list in **markdown**
- a working hyperlink to another website

To practice typing in math mode, also include a LaTeX formula describing how your final grade is going to be calculated based on the syllabus, something like:

$$grade = weight_1*score_1 + weight_2*score_2$$

Please be **brief** in your text.

# International Government and Politics

## Standard of Living in the EU
Here, standard of living will be measued using the Human Development Index (HDI). It is a grading scheme developed by the United Nations and it focuses on education, life expectancy, and people rather than just economic output

![Image of the EU](https://maproom.net/wp-content/uploads/EU-simple-map-preview.png)


Heres a [list of all European Union members by HDI](https://www.theglobaleconomy.com/rankings/human_development/European-union/)

### Factors HDI uses to calculate score
1. Life Expectancy Index
2. Education Index
3. Income Index

Final Score is geometric mean of these three indecies. For a detailed explenation of how these indecies work please see [the calculation part of this page](https://en.wikipedia.org/wiki/Human_Development_Index#New_method_(2010_HDI_onwards))

### Top 5 EU member states by HDI
| Country | HDI Score |
| ------- | --------- |
| Denmark | .962      |
| Germany | .959      |
| Sweden | .959     |
| Netherlands  | .955      |
| Belgium | .951      |

# Grading Formula

$$Grade = lab_1*.1 + lab_2*.1 + lab_3*.1 + hw_1*.15 + hw_2*.15 + quiz_1*.2 + quiz_2*.2$$

# Part 2: Numpy
## Part 2.1: Creating Arrays (10 points)

Create the following two arrays using the NumPy library and then print them out. Call the first array `array_a` and the second array `array_b` (make sure you keep the `import` statement below):

$$\mathbf{array_a} = \begin{bmatrix}3 & 8 & -2 & 3\\
.5 & -1 & 6 & 4\\
-5 & 7 & -42 & 2
\end{bmatrix}$$

$$\mathbf{array_b} = \begin{bmatrix}42 & 38 & 34\\
30 & 26 & 22\\
18 & 14 & 10\\
6 & 2 & -2\\
-6 & -10 & -14
\end{bmatrix}$$

In [23]:
# make sure to import numpy library
import numpy as np

In [24]:
array_a = np.array([[3,9,-2,3],
                    [.5,-1,6,4],
                    [-5,7,-42,2]])

array_b = np.array([[42,38,34],
                    [30,26,22],
                    [18,14,10],
                    [6,2,-2],
                    [-6,-10,-14]])

In [25]:
# uncomment below to print array_a
array_a

array([[  3. ,   9. ,  -2. ,   3. ],
       [  0.5,  -1. ,   6. ,   4. ],
       [ -5. ,   7. , -42. ,   2. ]])

In [26]:
# uncomment below to print array_b
array_b

array([[ 42,  38,  34],
       [ 30,  26,  22],
       [ 18,  14,  10],
       [  6,   2,  -2],
       [ -6, -10, -14]])

## Part 2.2: Exploring Arrays (15 points)

1. Give the shape, size, ndim, and nbytes for each of the two arrays.
1. Take the transpose of both arrays. Call these `t_array_a` and `t_array_b`.
1. Try to add `array_a` and `t_array_b` (*prove* and *show* you did this with commented out code), then remove the last column of `t_array_b` and try to add them again. In a markdown cell, explain what happened.

In [27]:

print(f"array_a nbytes: {array_a.nbytes}")
print(f"\n array_b nbytes: {array_b.nbytes}")

print(f"\n array_a ndim: {array_a.ndim}")
print(f"\n array_b ndim: {array_b.ndim}")

print(f"\n array_a shape: {array_a.shape}")
print(f"\n array_b shape: {array_b.shape}")

print(f"\n array_a size: {array_a.size}")
print(f"\n array_b size: {array_b.size}")

t_array_a = np.transpose(array_a)
t_array_b = np.transpose(array_b)

#np.add(array_a, t_array_b)
t_array_b = np.delete(t_array_b, 4, 1)
np.add(array_a, t_array_b)

array_a nbytes: 96

 array_b nbytes: 120

 array_a ndim: 2

 array_b ndim: 2

 array_a shape: (3, 4)

 array_b shape: (5, 3)

 array_a size: 12

 array_b size: 15


array([[ 45. ,  39. ,  16. ,   9. ],
       [ 38.5,  25. ,  20. ,   6. ],
       [ 29. ,  29. , -32. ,   0. ]])

Trying to add the two arrays without removing the column gives you this ValueError: ValueError: operands could not be broadcast together with shapes (3,4) (3,5)
When you delete the extra column in t_array_b the addition works without error.

# Part 3: Pandas
## Part 3.1: Reading in Data (5 points)

On Canvas is the `train_stations_europe.csv` file. It was adapted from [this Kaggle data set](https://www.kaggle.com/datasets/headsortails/train-stations-in-europe). Read this data set in, using the `id` as the index column, and print the first few rows of the data. Make sure you keep the `import` statement below!

In [28]:
# make sure to import pandas library
import pandas as pd

In [29]:
df = pd.read_csv("train_stations_europe.csv", index_col="id")
print(df.head())

                       name   latitude  longitude  parent_station_id country  \
id                                                                             
1   Chateau-Arnoux-St-Auban  44.081790   6.001625                NaN      FR   
2   Chateau-Arnoux-St-Auban  44.061565   5.997373                1.0      FR   
3     Chateau-Arnoux Mairie  44.063863   6.011248                1.0      FR   
4           Digne-les-Bains  44.350000   6.350000                NaN      FR   
6           Digne-les-Bains  44.088710   6.222982                4.0      FR   

       time_zone  is_city  is_main_station  is_airport  
id                                                      
1   Europe/Paris     True            False       False  
2   Europe/Paris    False             True       False  
3   Europe/Paris    False            False       False  
4   Europe/Paris     True            False       False  
6   Europe/Paris    False             True       False  


## Part 3.2: Manipulating Data (20 points)

1. Create a subset of the data set which (a) **includes** only train stations in Belgium and (b) **excludes** all train stations which are **not** in a city. Make sure to save this subset as a new data frame and print the first few rows of the data.
1. Use the `.describe()` function to produce summary statistics for the subset from the previous part. Create a markdown cell and explain:
    - What Series did the `.describe()` function run on? What Series did it not run on? What is the difference, and what does this mean the `.describe()` function is used for?

In [30]:
subset = df[(df["country"] == "BE") & (df["is_city"] == False)]
print(subset.head())
subset.describe()

                   name   latitude  longitude  parent_station_id country  \
id                                                                         
1121  Tournai Frontiere        NaN        NaN                NaN      BE   
1122          Froyennes        NaN        NaN                NaN      BE   
1313           Mouscron        NaN        NaN                NaN      BE   
1354    Quevy Frontiere        NaN        NaN             6003.0      BE   
5893     Bruxelles-Midi  50.835374   4.335695             5974.0      BE   

            time_zone  is_city  is_main_station  is_airport  
id                                                           
1121  Europe/Brussels    False            False       False  
1122  Europe/Brussels    False            False       False  
1313  Europe/Brussels    False            False       False  
1354  Europe/Brussels    False            False       False  
5893  Europe/Brussels    False             True       False  


,latitude,longitude,parent_station_id
count,564.000000,564.000000,26.000000
mean,50.726795,4.479032,13945.846154
std,0.344543,0.703753,10417.120726
min,49.555984,2.601729,5964.000000
25%,50.497272,4.021254,5964.000000
50%,50.766161,4.410297,5974.000000
75%,50.978579,4.939891,25908.250000
max,51.462641,6.041335,29332.000000


It looks like it runs on the numeric series and ignores the strings. Like you see the ids, latitude, longitude but you dont see country code, timezone, or the boolean values. The difference is that describe runs on the numeric series and ignores the categorial ones. This would mean that the describe function is most useful for statistical analysis, it gives you the standard deviation, mean, and a general idea of what your dataset looks like.

# Part 4: GitHub (10 points)

The below process is obviously not necessary, but designed to give students with minimal Git experience some practice using Git in the command line. When you finish the first three parts of this lab, give one last restart and run all to this file. Then, go to the [DS 3000 GitHub](https://github.com/eaegerber/ds3000_summer26), fork it and then clone it to your local machine. Then:

- In the forked and cloned ds3000_summer26 repo, make a new branch (`git checkout -b lab-upload`)
- Create a folder with your name (as Dr. Gerber did)
- Navigate to that folder and place this jupyter notebook inside
- Add the file as the change to be committed (`git add .\Lab1_MyName.ipynb`)
- Check `git status`, your changes should be staged
- Commit the changes with a short message (`git commit -m "My message"`)
- Push the repository to GitHub (`git push origin lab-upload`)
- Navigate the the GitHub in the browser and create a pull request
- Once the pull request is merged, you can delete your branch in the "Pull Requests" tab in the browser
- Finally, upload the Lab to Gradescope. When you do so, it will give you the option to do it via GitHub; do that.
  - **Note**: you only have to do this for this assignment; future assignments can be uploaded directly to Gradescope